-- DataWraith Market Product Management Demo Schema
-- Five-table PostgreSQL schema for local-only chaos/security testing.

CREATE TABLE IF NOT EXISTS market_categories (
    id integer PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS market_suppliers (
    id integer PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    lead_time_days integer NOT NULL DEFAULT 3,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
    id integer PRIMARY KEY,
    category_id integer REFERENCES market_categories(id),
    supplier_id integer REFERENCES market_suppliers(id),
    sku text UNIQUE,
    name text NOT NULL,
    stock integer NOT NULL DEFAULT 0,
    price numeric(12, 2) NOT NULL DEFAULT 0,
    reorder_level integer NOT NULL DEFAULT 5,
    status text NOT NULL DEFAULT 'active',
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (stock >= 0),
    CHECK (price >= 0),
    CHECK (status IN ('active', 'draft', 'archived'))
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES products(id),
    movement_type text NOT NULL,
    quantity integer NOT NULL,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (movement_type IN ('purchase', 'sale', 'adjustment', 'return')),
    CHECK (quantity <> 0)
);

CREATE TABLE IF NOT EXISTS market_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES products(id),
    customer_email text NOT NULL,
    quantity integer NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (quantity > 0),
    CHECK (status IN ('pending', 'paid', 'packed', 'shipped', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_supplier_id ON products(supplier_id);
CREATE INDEX IF NOT EXISTS idx_products_stock ON products(stock);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_product_id ON inventory_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_market_orders_product_id ON market_orders(product_id);
